### ISSUE TITLE
Support the "simple" password_scheme

### ISSUE THREAD

**Issue by BigBlueHat** [hoodiehq/pouchdb-users#4]
Old CouchDB's and Cloudant only support the "simple" password scheme.

It'd be great if this library could be used with those.

For instance, I was using it on [BigBlueHat/clusers](http://github.com/BigBlueHat/clusers), but had to remove it to get that user creation form working on Cloudant.

Thanks!
:tophat:

**Comment by gr2m** [comment]
Hey @BigBlueHat, I’m super sorry I missed your issues, I haven’t watched this repository by accident and only found it now. Is this still an issue for you? Can you explain what you mean with "simple" password scheme? I guess we would need to add an `{scheme: 'simple'}` option and then it would store something else than a derived key and salt? Happy to accept a PR for it :)

**Comment by gr2m** [comment]
@BigBlueHat are you still interested in the feature? Otherwise I’d close it

**Comment by BigBlueHat** [comment]
@gr2m sorry I didn't see the earlier notification. I think it's fine to close. Cloudant is now completely Apache CouchDB 2.x and the older CouchDB's will be upgrading...one would think. If/when I desperately need this, I shall send a PR. :smile: Sorry I didn't need it badly enough earlier to do that. :wink:

Cheers!
:tophat:
